// SPDX-License-Identifier: AGPL-3.0-only

// Per-question stand-in pools, locked verbatim from spec §6.
// Used by:
//   - the profanity filter (step 7): replaces matched words silently
//   - the round runner (step 6): bot/timer-expiry auto-fill source

import type { Language } from '../types.js';

export const STANDINS: Record<Language, Record<number, string[]>> = {
  en: {
    0: [
      'a sleepy llama',
      "the librarian's evil twin",
      'a confused penguin',
      'an overconfident raccoon',
      'a time-traveling accountant',
      "the world's smallest dragon",
      'a haunted vending machine',
      'a retired superhero named Gerald',
      'a suspicious houseplant',
      'three children in a trench coat',
    ],
    1: [
      'with a haunted toaster',
      'with three angry geese',
      'with a philosophical goldfish',
      "with someone who wouldn't stop humming",
      'with a cardboard cutout of a celebrity',
      'with an invisible best friend',
      'with a goat named Professor Cheese',
      'with a very lost tourist',
      'with a robot who only speaks in riddles',
      'with their imaginary accountant',
    ],
    2: [
      'inside a cheese factory',
      'at the bottom of the ocean',
      'in a library that only holds cookbooks',
      'on top of a moving bus',
      'inside a giant sock drawer',
      'at a very sad birthday party',
      "in the world's smallest elevator",
      'behind the sofa',
      'at a conference for people named Dave',
      'inside a cloud',
    ],
    3: [
      'during a minor earthquake',
      'at the exact moment of a solar eclipse',
      'right after breakfast but before second breakfast',
      "during someone else's wedding",
      'on a Tuesday that felt like a Wednesday',
      'when all the clocks stopped',
      'at 3am for no good reason',
      'during the annual hat festival',
      'when the internet went down',
      'at the precise moment a seagull made a decision',
    ],
    4: [
      'invented a new type of sadness',
      'attempted to bake an emotion',
      'tried to explain jazz to a brick wall',
      'reorganized the clouds by size',
      'started a strongly worded letter and never finished it',
      'accidentally became a local legend',
      'forgot how stairs work',
      'challenged a mirror to a staring contest',
      'declared war on Mondays',
      'tried to refund a rainbow',
    ],
    5: [
      'for reasons that made sense at the time',
      'to impress a pigeon',
      'because the warranty said not to',
      'in exchange for a single grape',
      'because someone dared them and they never back down',
      'to prove a point nobody asked about',
      'for science (unverified)',
      'out of spite',
      'because the horoscope was very specific',
      'to settle a bet with themselves',
    ],
    6: [
      'everyone had strong feelings about pasta',
      'a duck filed a formal complaint',
      'nothing made sense but everyone felt fine about it',
      'the receipts were lost and that was probably for the best',
      'several pigeons received certificates',
      'the mayor sent a fruit basket',
      'a sequel was immediately greenlit',
      'it was declared a public holiday in three countries',
      'the cloud that had been watching finally looked away',
      'everyone agreed never to speak of it again',
    ],
  },
  ru: {
    0: [
      'сонная лама',
      'злой близнец библиотекаря',
      'растерянный пингвин',
      'самоуверенный енот',
      'бухгалтер-путешественник во времени',
      'самый маленький дракон в мире',
      'проклятый автомат с едой',
      'пенсионер-супергерой по имени Гена',
      'подозрительный комнатный цветок',
      'трое детей в одном плаще',
    ],
    1: [
      'с проклятым тостером',
      'с тремя злобными гусями',
      'с философской золотой рыбкой',
      'с тем, кто не переставал мычать',
      'с картонной копией знаменитости',
      'с невидимым лучшим другом',
      'с козой по имени Профессор Сыр',
      'с очень заблудившимся туристом',
      'с роботом, говорящим только загадками',
      'со своим воображаемым бухгалтером',
    ],
    2: [
      'внутри сырного завода',
      'на дне океана',
      'в библиотеке, где только кулинарные книги',
      'на крыше движущегося автобуса',
      'в ящике с носками',
      'на очень грустном дне рождения',
      'в самом маленьком лифте в мире',
      'за диваном',
      'на конференции людей по имени Игорь',
      'внутри облака',
    ],
    3: [
      'во время небольшого землетрясения',
      'в момент солнечного затмения',
      'сразу после завтрака, но до второго завтрака',
      'на чужой свадьбе',
      'во вторник, похожий на среду',
      'когда все часы остановились',
      'в три часа ночи без причины',
      'во время ежегодного фестиваля шляп',
      'когда пропал интернет',
      'в момент, когда чайка приняла важное решение',
    ],
    4: [
      'придумал новый вид грусти',
      'попытался испечь эмоцию',
      'объяснял джаз кирпичной стене',
      'сортировал облака по размеру',
      'начал серьёзное письмо и не закончил',
      'случайно стал местной легендой',
      'забыл как работают лестницы',
      'вступил в конкурс по гляделкам с зеркалом',
      'объявил войну понедельникам',
      'попытался вернуть радугу в магазин',
    ],
    5: [
      'по причинам, которые тогда казались разумными',
      'чтобы впечатлить голубя',
      'потому что гарантия запрещала',
      'в обмен на одну виноградину',
      'потому что поспорили и они никогда не отступают',
      'чтобы доказать никому не нужную точку зрения',
      'во имя науки (не подтверждено)',
      'из вредности',
      'потому что гороскоп был очень конкретен',
      'чтобы урегулировать спор с самим собой',
    ],
    6: [
      'у всех были сильные чувства по поводу пасты',
      'утка подала официальную жалобу',
      'ничего не имело смысла, но всем было хорошо',
      'чеки потерялись и это было к лучшему',
      'несколько голубей получили сертификаты',
      'мэр прислал фруктовую корзину',
      'сиквел немедленно получил зелёный свет',
      'это объявили праздником в трёх странах',
      'облако, которое наблюдало, наконец отвернулось',
      'все согласились никогда больше не говорить об этом',
    ],
  },
};

export function pickStandin(language: Language, questionIndex: number): string {
  const pool = STANDINS[language][questionIndex];
  if (!pool || pool.length === 0) return '???';
  return pool[Math.floor(Math.random() * pool.length)]!;
}
